config/routes.rb
Bddatcgi::Application.routes.draw do



  root to: 'user_sessions#new'

  match 'sign_in'  => 'user_sessions#new',     as: :sign_in
  match 'sign_out' => 'user_sessions#destroy', as: :sign_out

  resources :user_sessions, only: [:new, :create, :destroy]

  match 'sign_up' => 'registrations#new',              via: :get,  as: :sign_up
  match 'sign_up' => 'registrations#create',           via: :post, as: :sign_up
  match 'activate/:token' => 'registrations#activate', via: :get,  as: :activation

  match 'forgotten_password' => 'password_resets#new',     via: :get,  as: :forgotten_password
  match 'forgotten_password' => 'password_resets#create',  via: :post, as: :forgotten_password
  match 'reset_password/:token' => 'password_resets#edit', via: :get,  as: :reset_password
  match 'reset_password/:id' => 'password_resets#update',  via: :put

  resources :users do
    resources :jira_accounts do
      resources :feature_requests, :only => [:create, :new]
    end
  end

end

app/models/jira_account.rb
require 'jira'
class JiraAccount < ActiveRecord::Base
  attr_accessible :password, :username
  belongs_to :user
  validates_uniqueness_of :username, :scope => [:user_id]
  validates_presence_of :password
  validates_presence_of :username
  validates :password, :with => :jira_credentials
  attr_encrypted :password, :key => :encryption_key
  URL= 'https://www.cws-cgicloud-apps.com:8443'

  def jira
    @jira ||= JIRA::Client.new(credentials)
  end

  def credentials
     {
      :username => self.username,
      :password => self.password, 
      :site => URL,
      :context_path => '',
      :auth_type => :basic

    }
  end

  def find_story_by(issuekey)
    if jira_credentials
      begin
        @issue ||= jira.Issue.find(issuekey) 
      rescue
        raise "Issue Not Found. Please enter a valid JIRA ID"
      end
    end

  end

  def test_cases_for(story)
    if story
        @test_cases ||= story.issuelinks.select { |i| i["type"]["name"] == "Test Case" }
        @tests ||= @test_cases.collect {|t| t["inwardIssue"]["key"] }
    else
      raise "User Story Not Found. Please enter a valid JIRA ID"
    end
  end

  def feature_file_for(issuekey)
    string = ''
    issuetitle = issuekey
    if story = find_story_by(issuekey)
      raise 'No test cases were related to the Issue ID provided' unless test_cases_for(story).any?
      string << <<-STORY
      Feature: #{issuetitle} \n
      #{story.description} \n
      #{story.customfield_10116} \n \n \n
      STORY
      test_cases_for(story).each do |test_case_id|
        tc = jira.Issue.find(test_case_id)  rescue nil
        if tc
          string << <<-STRING
          #{tc.summary} \n
          #{tc.description}\n\n
          STRING
        end
      end
    end
    return string,friendly_filename(story.summary)
  end


  def jira_credentials
    puts jira
    puts credentials
    jira.Issuetype.all rescue raise "Invalid username and /or password. If you think you have the right credentials, log out and log back into your JIRA web account"
  end

  def friendly_filename(filename)
      filename.gsub(/[^\w\s_-]+/, '')
              .gsub(/(^|\b\s)\s+($|\s?\b)/, '\\1\\2')
              .gsub(/\s+/, '_')
  end

  def encryption_key
    created_date = self.new_record? ? Date.today : self.created_at.to_date 
    Base64.encode64(created_date.to_s)
  end
  

end 

app/controllers/jira_accounts_controller.rb
class JiraAccountsController < ApplicationController

  load_and_authorize_resource
  before_filter :load_user

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @jira_account = @user.jira_accounts.build(params[:jira_account])
    if @jira_account.save
      redirect_to user_jira_account_path(@user, @jira_account), notice: 'Jira account was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    if @jira_account.update_attributes(params[:jira_account])
      redirect_to user_jira_account_path(@user, @jira_account), notice: 'Jira account was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @jira_account.destroy
    redirect_to user_jira_accounts_url
  end


 
end

app/helpers/jira_accounts_helper.rb
module JiraAccountsHelper
end

app/views/jira_accounts/_form.html.slim
= simple_form_for([@user, @jira_account]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :username, autofocus: true
    = f.label :password
    = f.password_field :password

  .form-actions
    = f.button :submit, class: 'btn btn-primary'
    '
    = link_to 'Back', user_jira_accounts_path, class: 'btn'

app/views/jira_accounts/edit.html.slim
.page-header
  h1 Editing JIRA Account

== render 'form'

app/views/jira_accounts/index.html.slim
div.page-header
  h1 Your JIRA Accounts 

table.table.table-striped
  thead
    tr
      th ID
      th Username
      th Actions

  tbody
  - @jira_accounts.each do |jira_account|
    tr
      td= link_to_if can?(:show, jira_account), jira_account.id, user_jira_accounts_path(current_user,jira_account)
      td= jira_account.username
      td
        - if can? :edit, jira_account
          = link_to 'Edit', edit_user_jira_account_path(current_user,jira_account), class: 'btn btn-mini'
          '
        - if can? :destroy, jira_account
          = link_to 'Delete', user_jira_account_path(current_user,jira_account), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-mini btn-danger'
          '
          = link_to "Get Feature File", new_user_jira_account_feature_request_path(current_user, jira_account),class: 'btn btn-mini btn-info'

- if can? :create, JiraAccount
  = link_to 'New Jira account', new_user_jira_account_path, class: 'btn btn-primary'

app/views/jira_accounts/new.html.slim
.page-header
  h1 Create JIRA Account

== render 'form'

app/views/jira_accounts/show.html.slim
.page-header
  h1 JIRA Account

dl
  dt Username
  dd= @jira_account.username

- if can?(:edit, @jira_account)
  = link_to 'Edit', edit_user_jira_account_path(current_user, @jira_account), class: 'btn'
  '
= link_to 'Back', user_jira_accounts_path, class: 'btn'

- if can?(:destroy, @jira_account)
  '
  = link_to'Destroy', user_jira_accounts_path(current_user, @jira_account), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger'