config/routes.rb
Bddatcgi::Application.routes.draw do



  root to: 'user_sessions#new'

  match 'sign_in'  => 'user_sessions#new',     as: :sign_in
  match 'sign_out' => 'user_sessions#destroy', as: :sign_out

  resources :user_sessions, only: [:new, :create, :destroy]

  match 'sign_up' => 'registrations#new',              via: :get,  as: :sign_up
  match 'sign_up' => 'registrations#create',           via: :post, as: :sign_up
  match 'activate/:token' => 'registrations#activate', via: :get,  as: :activation

  match 'forgotten_password' => 'password_resets#new',     via: :get,  as: :forgotten_password
  match 'forgotten_password' => 'password_resets#create',  via: :post, as: :forgotten_password
  match 'reset_password/:token' => 'password_resets#edit', via: :get,  as: :reset_password
  match 'reset_password/:id' => 'password_resets#update',  via: :put

  resources :users do
    resources :jira_accounts do
      resources :feature_requests, :only => [:create, :new]
    end
  end

end

app/views/layouts/application.html.slim
doctype 5
html
  head
    title BDD Helper
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tag

  body id=(controller.controller_name) class=(controller.action_name)
    .wrapper
      .container
        header.navbar.navbar-fixed-top
          nav.navbar-inner
            .container
              .brand 
                = link_to image_tag('CGILogo.png', :size => '50x20'), root_url
                'Experience BDD
              ul.nav.pull-right
                - if current_user
                  li.dropdown
                    a.dropdown-toggle href='#' data-toggle='dropdown'
                      = current_user.email
                      b.caret
                    ul.dropdown-menu
                      li= link_to 'Sign Out', sign_out_path
                    li= link_to 'My Accounts', user_jira_accounts_path(current_user)
                - else
                  li= link_to 'Sign In', sign_in_path

        - flash.each do |name, msg|
          = content_tag :div, raw(msg), class: "alert #{alert_class(name)}"

        = yield

      .push

    footer
      .container
        p &copy; 2013 All rights reserved.